# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../../custom_download_strategy"
class Dust < Formula
  desc "Run developer tasks and tools"
  homepage "https://github.com/macrocosm-os/dust"
  version "0.1.5"

  depends_on "macrocosm-os/platform/dust-tools"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/macrocosm-os/dust/releases/download/v0.1.5/dust_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e564b6014eb3a04abcde5c902f95953174afabfe75c272aa3c7a02e97ec37cfe"

      def install
        bin.install "dust"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/macrocosm-os/dust/releases/download/v0.1.5/dust_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fe5186f1662b72a1caf036fb15af225a1b67c57d30ae7418fe072120d641ad29"

      def install
        bin.install "dust"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/macrocosm-os/dust/releases/download/v0.1.5/dust_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "f3feed6c87ba91e2244314b383f045a6b07c58ae15ab25c9e3a947325652af1e"

        def install
          bin.install "dust"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/macrocosm-os/dust/releases/download/v0.1.5/dust_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "87aeb8e0d6f2bc0fc901ec64ea8566115d9f1850045a1c6b2744e52d1b643d60"

        def install
          bin.install "dust"
        end
      end
    end
  end

  conflicts_with "dust"
  conflicts_with "metafeather/tools/dust"
end
