# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../../custom_download_strategy"
class Dust < Formula
  desc "Run developer tasks and tools"
  homepage "https://github.com/macrocosm-os/dust"
  version "0.1.4"

  depends_on "macrocosm-os/platform/dust-tools"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/macrocosm-os/dust/releases/download/v0.1.4/dust_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryDownloadStrategy
      sha256 "ce9a2bae5dd287153a93bf7e20f5d29cf458523f1cd6a21153914aee6ce53429"

      def install
        bin.install "dust"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/macrocosm-os/dust/releases/download/v0.1.4/dust_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryDownloadStrategy
      sha256 "90d27f3196d8361e0ebd61071b90a99be45a039916decc44973da19e6e5a7c50"

      def install
        bin.install "dust"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/macrocosm-os/dust/releases/download/v0.1.4/dust_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryDownloadStrategy
        sha256 "1f9df40896340242d05f15176184f6e7ce6884c0d604b0dc6dc95c2477bddcaa"

        def install
          bin.install "dust"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/macrocosm-os/dust/releases/download/v0.1.4/dust_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryDownloadStrategy
        sha256 "d1d947738e1533f3fb7a0178caaa9220b7341d7451dc1a375ac71c80dc453586"

        def install
          bin.install "dust"
        end
      end
    end
  end

  conflicts_with "dust"
  conflicts_with "metafeather/tools/dust"
end
