# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../../custom_download_strategy"
class Dust < Formula
  desc "Run developer tasks and tools"
  homepage "https://github.com/macrocosm-os/dust"
  version "0.2.0"

  depends_on "macrocosm-os/platform/dust-tools"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/macrocosm-os/dust/releases/download/v0.2.0/dust_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "cb525b9e5cdd83bcbca9c3e499f742c622e573c02b93a2aeb821436f41dc87e8"

      def install
        bin.install "dust"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/macrocosm-os/dust/releases/download/v0.2.0/dust_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "4bd9f8bf0d779edebf72a637e889487fb756bed95bad97ba7cd4e89c1f6792e1"

      def install
        bin.install "dust"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/macrocosm-os/dust/releases/download/v0.2.0/dust_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "c3b04fb34436b99b512cd7e9e08f27da9106ba67830d94b41c4a8a1c57bcd1a4"

        def install
          bin.install "dust"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/macrocosm-os/dust/releases/download/v0.2.0/dust_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "77cd880ab28ace2b7696911010b8bdf292e5e8b13563b6da436f181483d8409f"

        def install
          bin.install "dust"
        end
      end
    end
  end

  conflicts_with "dust"
  conflicts_with "metafeather/tools/dust"
end
